### ISSUE TITLE
Getting an error trying to use firstling!

### ISSUE THREAD

**Issue by bryantorresvega** [pensierinmusica/firstline#1]
`Bryans-MacBook-Pro:PRSN bryantorres$ node readtxt.js

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:351:3)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/bryantorres/Desktop/PRSN/readtxt.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

Any help on how to fix this?

**Comment by pensierinmusica** [comment]
Hi, to better assist you can you please copy here the content of your file `readtxt.js`? Thanks!
